inventory:
  plugin: SimpleInventory
  options:
    host_file: "inventory/hosts.yaml"
    group_file: "inventory/groups.yaml"
  transform_function: "load_credentials"
runner:
  plugin: threaded
  options:
    num_workers: 100